#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PY_BIN="${PY_BIN:-python3.10}"
BENT_VERSION="0.0.80"
FRONTEND_ENV_FILE="$ROOT/frontend/.env.local"

usage() {
  cat <<'EOF'
Usage:
  scripts/setup_bent_runtime.sh

Optional env vars:
  PY_BIN     Python executable for local mode (default: python3.10)
  RUN_SETUP  Set to 1 to run bent_setup during installation (default: 0)

Examples:
  PY_BIN=python3.10 ./scripts/setup_bent_runtime.sh
  RUN_SETUP=1 ./scripts/setup_bent_runtime.sh
EOF
}

if [[ "${1-}" != "" ]]; then
  echo "Error: this script no longer accepts positional arguments."
  echo
  usage
  exit 1
fi

set_frontend_mode() {
  local api_base="$1"
  mkdir -p "$(dirname "$FRONTEND_ENV_FILE")"
  cat > "$FRONTEND_ENV_FILE" <<EOF
# Auto-generated by scripts/setup_bent_runtime.sh
# Keep backend target explicit for local runs.
VITE_API_BASE=${api_base}
EOF
}

check_python310_mode() {
  local version
  version="$("$PY_BIN" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")')"
  if [[ "$version" != 3.10.* ]]; then
    echo "Local bent runtime needs Python 3.10.x (this interpreter is $version)."
    exit 1
  fi

  local patch
  patch="$(echo "$version" | awk -F. '{print $3}')"
  if [[ -z "$patch" ]] || (( patch > 13 )); then
    echo "Bent requires Python <=3.10.13, but this interpreter is $version."
    exit 1
  fi
}

install_local_bent() {
  if ! command -v "$PY_BIN" >/dev/null 2>&1; then
    echo "Python executable '$PY_BIN' not found."
    echo "Set PY_BIN to a valid Python 3.10.x interpreter and retry."
    exit 1
  fi

  check_python310_mode

  echo "Installing bent ${BENT_VERSION} into $(command -v "$PY_BIN")..."
  "$PY_BIN" -m pip install --upgrade pip
  "$PY_BIN" -m pip install "bent==${BENT_VERSION}"

  if [[ "${RUN_SETUP:-0}" == "1" ]]; then
    if command -v bent_setup >/dev/null 2>&1; then
      echo "Running bent_setup to download built-in knowledge bases..."
      TF_CPP_MIN_LOG_LEVEL=3 bent_setup
    else
      echo "bent was installed, but bent_setup is not on PATH."
      echo "Run 'bent_setup' from the same environment to complete optional Bent KB setup."
    fi
  else
    echo "To prepare Bent knowledge bases, run:"
    echo "  bent_setup"
  fi

  set_frontend_mode "http://127.0.0.1:8000"
  echo "Frontend env written to ${FRONTEND_ENV_FILE} (mode=local)."
}

install_local_bent

