#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE_FILE="${COMPOSE_FILE:-$ROOT/docker-compose.yml}"
RUN_SETUP="${RUN_SETUP:-1}"
WRITE_ENV="${WRITE_ENV:-1}"
FRONTEND_ENV_FILE="$ROOT/frontend/.env.local"

usage() {
  cat <<'EOF'
Usage:
  scripts/setup_docker_bent.sh

Environment:
  RUN_SETUP  Set to 0 to skip running `bent_setup` (default: 1)
  WRITE_ENV  Set to 1 to write frontend/.env.local with VITE_API_BASE=/api (default: 1)
  COMPOSE_FILE  Path to docker compose file (default: docker-compose.yml)

Examples:
  ./scripts/setup_docker_bent.sh
  RUN_SETUP=0 WRITE_ENV=0 ./scripts/setup_docker_bent.sh
EOF
}

if command -v docker >/dev/null 2>&1; then
  : # pass
else
  echo "Docker is required for this script."
  exit 1
fi

if [[ "${1-}" != "" ]]; then
  echo "No positional arguments are supported."
  usage
  exit 1
fi

echo "Starting bent-runtime service with compose profile 'bent'..."
docker compose --file "$COMPOSE_FILE" --profile bent up -d bent-runtime
echo "Bent service URL (container network): http://bent-runtime:8010"

if [[ "${RUN_SETUP}" == "1" ]]; then
  echo "Running bent_setup in bent-runtime container..."
  docker compose --file "$COMPOSE_FILE" --profile bent exec bent-runtime bent_setup
else
  echo "Skipped automatic bent_setup. Run manually:"
  echo "  docker compose --file \"$COMPOSE_FILE\" --profile bent exec bent-runtime bent_setup"
fi

if [[ "${WRITE_ENV}" == "1" ]]; then
  mkdir -p "$(dirname "$FRONTEND_ENV_FILE")"
  cat > "$FRONTEND_ENV_FILE" <<'EOF'
# Auto-generated by scripts/setup_docker_bent.sh
# Compose frontend uses /api proxy by default.
VITE_API_BASE=/api
EOF
  echo "Frontend env written to ${FRONTEND_ENV_FILE}."
fi

