#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PY_BIN="${PY_BIN:-python3.10}"
BENT_VERSION="0.0.80"
# Bent 0.0.80 requires an exact spaCy pin on Python 3.10.
BENT_SPACY_VERSION="3.7.2"
# Bent 0.0.80 depends on pkg_resources from legacy setuptools behavior.
BENT_SETUPTOOLS_VERSION="65.5.0"
BENT_VENV="${BENT_VENV:-$ROOT/.venv-bent}"
FRONTEND_ENV_FILE="$ROOT/frontend/.env.local"

usage() {
  cat <<'EOF'
Usage:
  scripts/setup_bent_runtime.sh

Optional env vars:
  PY_BIN     Python executable for creating the runtime environment (default: python3.10)
  BENT_VENV  Virtualenv path for Bent runtime (default: <repo>/.venv-bent)
  RUN_SETUP  Set to 1 to run bent_setup during installation (default: 0)

Examples:
  PY_BIN=python3.10 ./scripts/setup_bent_runtime.sh
  BENT_VENV="$PWD/.venv-bent" ./scripts/setup_bent_runtime.sh
  RUN_SETUP=1 ./scripts/setup_bent_runtime.sh
EOF
}

if [[ "${1-}" != "" ]]; then
  echo "Error: this script no longer accepts positional arguments."
  echo
  usage
  exit 1
fi

set_frontend_mode() {
  local api_base="$1"
  mkdir -p "$(dirname "$FRONTEND_ENV_FILE")"
  cat > "$FRONTEND_ENV_FILE" <<EOF
# Auto-generated by scripts/setup_bent_runtime.sh
# Keep backend target explicit for local runs.
VITE_API_BASE=${api_base}
EOF
}

check_python310_mode() {
  local version
  version="$("$PY_BIN" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")')"
  if [[ "$version" != 3.10.* ]]; then
    echo "Local bent runtime needs Python 3.10.x (this interpreter is $version)."
    exit 1
  fi

  local patch
  patch="$(echo "$version" | awk -F. '{print $3}')"
  if [[ -z "$patch" ]] || (( patch > 13 )); then
    echo "Bent requires Python <=3.10.13, but this interpreter is $version."
    exit 1
  fi
}

check_venv_python_mode() {
  local venv_python="$1"
  local version
  version="$("$venv_python" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")')"
  if [[ "$version" != 3.10.* ]]; then
    echo "Bent runtime virtualenv is not Python 3.10.x (this interpreter is $version)."
    echo "Delete ${BENT_VENV} and rerun this script to recreate it with Python 3.10."
    exit 1
  fi

  local patch
  patch="$(echo "$version" | awk -F. '{print $3}')"
  if [[ -z "$patch" ]] || (( patch > 13 )); then
    echo "Bent requires Python <=3.10.13, but this environment is $version."
    echo "Delete ${BENT_VENV} and rerun this script to recreate it with Python <=3.10.13."
    exit 1
  fi
}

ensure_bent_env() {
  local venv_python="$BENT_VENV/bin/python"

  if [[ -d "$BENT_VENV" ]]; then
    if [[ ! -x "$venv_python" ]]; then
      echo "Existing BENT_VENV path '${BENT_VENV}' is invalid (missing virtualenv Python binary)."
      echo "Delete it or set BENT_VENV to a different path."
      exit 1
    fi
    echo "Reusing existing Bent runtime virtualenv at ${BENT_VENV}."
  else
    echo "Creating dedicated virtualenv for Bent at ${BENT_VENV}..."
    "$PY_BIN" -m venv "$BENT_VENV"
  fi

  check_venv_python_mode "$venv_python"

  local venv_python_basename
  venv_python_basename="$(basename "$venv_python")"
  if [[ ! -x "$BENT_VENV/bin/$venv_python_basename" ]]; then
    echo "Bent runtime virtualenv setup is incomplete."
    exit 1
  fi
}

install_bent_in_env() {
  local venv_python="$BENT_VENV/bin/python"
  local venv_pip="$BENT_VENV/bin/pip"
  local bent_setup="$BENT_VENV/bin/bent_setup"

  "$venv_python" -m pip install --upgrade pip
  "$venv_pip" install "setuptools==${BENT_SETUPTOOLS_VERSION}" "spacy==${BENT_SPACY_VERSION}" "bent==${BENT_VERSION}"

  if [[ "${RUN_SETUP:-0}" == "1" ]]; then
    if [[ -x "$bent_setup" ]]; then
      echo "Running bent_setup in ${BENT_VENV}..."
      "$bent_setup"
    else
      echo "bent was installed, but bent_setup is not available in ${BENT_VENV}."
      echo "If needed, run:"
      echo "  ${bent_setup}"
    fi
  else
    echo "To prepare Bent knowledge bases, run:"
    echo "  ${bent_setup}"
  fi

  echo "Bent runtime environment ready at: ${BENT_VENV}"
}

install_local_bent() {
  if ! command -v "$PY_BIN" >/dev/null 2>&1; then
    echo "Python executable '$PY_BIN' not found."
    echo "Set PY_BIN to a valid Python 3.10.x interpreter and retry."
    exit 1
  fi

  check_python310_mode

  ensure_bent_env
  install_bent_in_env

  set_frontend_mode "http://127.0.0.1:8000"
  echo "Frontend env written to ${FRONTEND_ENV_FILE} (mode=local)."
  echo "To use Bent, run commands inside ${BENT_VENV}:"
  echo "  source \"${BENT_VENV}/bin/activate\""
}

install_local_bent

